apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: v1.25.2 # Replace with the istio-ingress version you'd like to install or upgrade to
      helm:
        valueFiles: 
        - $values/istio-ingress-values.yaml
    - repoURL: 'https://github.com/wartoz/istio.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress