apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
      version: v1
  template:
    metadata:
      labels:
        app: order-management
        version: v1
    spec:
      containers:
      - name: order-management
        image: rslim087/order-management:1.0.0
        ports:
        - containerPort: 9090
        env:
        - name: PRODUCT_INVENTORY_API_HOST
          value: "http://product-inventory"
        - name: PRODUCT_CATALOG_API_HOST
          value: "http://product-catalog"
        - name: SHIPPING_HANDLING_API_HOST
          value: "http://shipping-and-handling"
---
apiVersion: v1
kind: Service
metadata:
  name: order-management
  namespace: ecommerce
spec:
  ports:
  - port: 9090
    name: http
  selector:
    app: order-management